# Generated by Django 4.2.3 on 2024-08-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('website', models.URLField()),
                ('objective', models.TextField()),
                ('education1', models.TextField()),
                ('education2', models.TextField()),
                ('technical_skills', models.TextField()),
                ('soft_skills', models.TextField()),
                ('other_skills', models.TextField()),
                ('experience1', models.TextField()),
                ('experience2', models.TextField()),
                ('project1', models.TextField()),
                ('project2', models.TextField()),
                ('project3', models.TextField()),
                ('activities', models.TextField()),
                ('leadership', models.TextField()),
            ],
        ),
    ]
