# Generated by Django 4.2.3 on 2024-08-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='website',
        ),
    ]
