# Generated by Django 4.2.3 on 2024-08-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_remove_resume_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='experience2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='project3',
        ),
    ]
