# Generated by Django 4.2.3 on 2024-08-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_remove_resume_experience2_remove_resume_project3'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='leetcode',
            field=models.URLField(default=''),
        ),
    ]
