# Generated by Django 4.2.3 on 2024-08-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_resume_leetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(default=''),
        ),
    ]
